services:

  # local database for dev mode only
  development_database:
    profiles:
      - developement
      - dev
  # service for node server
  backend:
    build: ./server_side
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    env_file:
      - ./server_side/env/.env
      - ./server_side/env/.env.production
      - ./server_side/env/.env.developement
    environment:
      - PORT=${PORT:-3000}
      - NODE_ENV=${NODE_ENV:-developement}
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    depends_on:
      - frontend

  # redis service for caching

  # service to build react app
  frontend:
    build: ./client
    ports:
      - ${PORT:-5173}:${PORT:-5173}

volumes:
  redis_data:

 
